### ISSUE TITLE
Exported .iso files crash on certain stages

### ISSUE THREAD

**Issue by PKPenguin321** [akaneia/mexTool#9]
version.txt - 01/22/2021 05:03:05 +00:00

Reproduction steps:
- Load a vanilla melee iso (or any compatible .iso) into mexTool
- Export as .iso (making any number of changes including 0 does not matter)
- Run in Slippi and select pokefloats, FoD, kongo jungle, yoshis story, jungle japes, brinstar depths, melee brinstar, onett, or potentially others that I haven't tested
- Game will crash, Dolphin will sometimes throw infinite error messages

**Comment by aman601** [comment]
Also, the file size goes from around 1.4 gb to around 700 mb - not sure if this is expected but it could be removing something important with the data I assume it gets rid of
